### ISSUE TITLE
Add new pkgs to install

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#17]
I generated an iso and did a general installation. After that I wanted to generate a new customized iso and a number of packages where missing (needed to be installed manually).

Maybe it would be good to have them installed by default:

```
git tar gawk wget cdrkit syslinux
```

**Comment by tnut** [comment]
Normaly, when I install NuTyX I do not build packages neither do any commit. As most of the users does. 
I think it make not much sence to add packages that you propably will never use. 

If you are planning to build packages. It should be enought to do a

    $ get cards.devel

**Comment by peter1000** [comment]
Sorry I think you misunderstood me.

I did not build any packages but rebuild the customary iso like in our documentation: http://www.nutyx.org/en/generate-iso.html

Anyway no problem as we mentioned it in the docs: `cards install git tar gawk wget cdrkit syslinux`
