### ISSUE TITLE
Move packages: base, cli and gui to own repos

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#26]
Just a thought: Maybe it would be a good idea to move: **base, cli and gui** into there own repositories like you did with [extra](https://github.com/NuTyX/extra). 

For example: Repository: **main**

```
main
├── base
├── cli
└── gui
```

**Comment by tnut** [comment]
what is the prob to have that together. I found this very handy and convenient

**Comment by peter1000** [comment]
no problem at all: just thought that it would be more consistent if all packages have there own repo. and the development of *NuTyX* would contain just the other things.

Anyway, no problem at all.

**Comment by tnut** [comment]
The think is, houaphan git is also use for the building of a NuTyX. Means you need already the chroot, the scripts and the base directoty together. Having the www pages in this git is somehow wierd but so convenient as everything is related to everithing in this git. And don't forget. With this git you are already setup to do your own distro if you would like to. Those 3 collections base,cli and gui are the mandatory ones. All the others are just "nice to have"

**Comment by peter1000** [comment]
Ok, no problem at all.
