### ISSUE TITLE
Comment compiler qemu-static

### ISSUE THREAD

**Issue by tnut** [NuTyX/houaphan#38]
Si j'ajoute à la commande configure:
./configure --prefix=/usr --sysconfdir=/etc --enable-static --audio-drv-list=alsa,sdl --docdir=/usr/share/doc/qemu-2.4.1
ERROR: unknown option --enable-static
Try './configure --help' for more information

**Comment by berlius** [comment]
Ce n'est pas dans qemu qu'il faut mettre "--enable-static" mais dans les librairies. j'ai déjà mis son parametre "-static" dans la recette de qemu 
 

   

 On Saturday, March 5, 2016 8:08 PM, tnut <notifications@github.com> wrote:
 

 Si j'ajoute à la commande configure:
./configure --prefix=/usr --sysconfdir=/etc --enable-static --audio-drv-list=alsa,sdl --docdir=/usr/share/doc/qemu-2.4.1
ERROR: unknown option --enable-static
Try './configure --help' for more information—

**Comment by tnut** [comment]
Oui j'avais compris (après)
Je propose de décrire dans l'article pre-build-arm.html, la marche à suivre opour compiler qemu en statique

**Comment by berlius** [comment]
J'ai fais une recette particulière pour "qemu-static" que j'ai envoyé avec les autres recettes il y a deux jours. Elle est dans /extra/gui-extra en dessous de  "qemu" classique
 

    On Sunday, March 6, 2016 4:52 PM, berlius jean <berlius52@yahoo.com> wrote:
 

 Ce n'est pas dans qemu qu'il faut mettre "--enable-static" mais dans les librairies. j'ai déjà mis son parametre "-static" dans la recette de qemu 
 

   

 On Saturday, March 5, 2016 8:08 PM, tnut <notifications@github.com> wrote:
 

 Si j'ajoute à la commande configure:
./configure --prefix=/usr --sysconfdir=/etc --enable-static --audio-drv-list=alsa,sdl --docdir=/usr/share/doc/qemu-2.4.1
ERROR: unknown option --enable-static
Try './configure --help' for more information—

**Comment by tnut** [comment]
=======> WARNING: Footprint ignored.
=======> Adding meta data to Archive qemu-static
=======> compress qemu-static1457282455x86_64.cards.tar
Retrieve info about the 767 packages: 100 %
ADD    : qemu-static 2.5.0-2, 131 files: 100 %
CREATED: qemu-static 2.5.0
