### ISSUE TITLE
Should this line be removed?

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#43]
Maybe I'm mistaken but it seems that this line **<$PKGMK -d -cf ../../../bin/pkgmk.conf.passes -i>** is a historical left over: https://github.com/NuTyX/houaphan/blob/master/scripts/pass#L87 after the **exit 1** ?

```
	   bash)
		$PKGMK -cf ../../../bin/pkgmk.conf.passes -kw 2>&1|tee ${LOG}/$NAME.log || exit 1
		rm /bin/bash
		rm /bin/sh
		echo "need to install bash manually"
		echo "=======> Installing '$NAME' succeeded." >> ${LOG}/$NAME.log
		exit 1
		$PKGMK -d -cf ../../../bin/pkgmk.conf.passes -i
		;;

```

Before changing it see my pullrequest: https://github.com/NuTyX/houaphan/pull/41

**Comment by tnut** [comment]
I did check we really need it
