### ISSUE TITLE
Just something I noticed: build as root / not as root

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#44]
[Here we have](https://github.com/NuTyX/cards/blob/master/scripts/pkgmk.in#L774 )

**warning "Packages should be built as root."**

[And here we have](https://github.com/NuTyX/houaphan/blob/master/scripts/pkgmk.passes#L106)

**error "Packages should NOT be built as root."**

Not saying this is wrong as there are different cases - but just something I noticed and maybe to be adjusted.

**Comment by tnut** [comment]
That's correct. It has already save me a lot of time. Pass 1 should be done in a non root user. Pass2 and all the rezepts should be done as a root user. When this message comes I know directly something is wrong in my config

**Comment by peter1000** [comment]
Thanks for the explanation
