### ISSUE TITLE
Question: cards.pkg files

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#45]
Just out of curiosity: in most linux distributions the package file show a package version similar to the source.

I wonder why did you decide to leave this out and go with a number like:  **1456977099**

`cards.devel1456977099x86_64.cards.tar.xz`

I'm sure there must be a good reason - just wonder why?

Cheers
P

**Comment by tnut** [comment]
As you maybe knows already, cards don't care about the name of the binary, as it check always and find all the info it need by "reading the meta data inside the archive". As I had to find a way to make shure that the file available on the depot is really the one we need I had to find a good way to name it somehow uniquely. I found the epoc time a good way. In your example 1456977099 correspond to the build date of the binary (much more important then the release)

**Comment by peter1000** [comment]
:+1:  Thanks
