### ISSUE TITLE
Announcement: P-Linux

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#47]
hi @tnut,

**There are a couple of reasons why I decided to try, my own NuTyX-Linux based system.**

* It seems you have a well tested (nearly 10 years or so)  system and I'm not sure committing all these changes from someone like me, who barely knows NuTyX-Linux  (read about it for the first time maybe 2 weeks ago), is a good idea.

* Doing a own system based on NuTyX-Linux will also force me to learn a bit more about *how you planned NuTyX-Linux to work* - which is a good thing if I want to use it as my main operating system.

* Also there are a lot of things in French (which I do not speak) and probably it's easier and faster to just write some English  or German notes from scratch as I skim through the code and installation.

* I'm still not sure if NuTyX-Linux is fitted for my purpose - but the parts I have checked out look good.
It may not be the best idea to make major code changes (like the pkgmk2 ;) to  your well tested system and in a couple of weeks I decide to stick with Arch or Gentoo.

---

**Of course, you are more than welcome to back-port any changes I make or reuse the documentation/notes I write.**

I also plan to give you feedback: as I skim through your code / documentation, and send one or the other pull-request.

**Probably this will also be a good thing for NuTyX-Linux**: having someone with a fresh outlook to check some of the scripts, documentations  and raising some questions....

---

If you want to check out my progress:

[P-Linux organization](https://github.com/P-Linux)

```
A NuTyX-Linux derived Linux system for 64-bit (x86_64) architecture.
```

P

**Comment by tnut** [comment]
About the missing english documentation, I would say go on with it, It's wouln'd be waste of time. That's for me the best way to learn. 

About your fork, why not. For me you where too fast, I couln'd follow all your pull requests.

Last sentence, I did get I think something is missing:
"It may not be the best idea to make major code changes (like the pkgmk2 ;) to your well tested system and in a couple of weeks I decide to stick with Arch or Gentoo."

**Comment by peter1000** [comment]
yes, I'm still not sure if NuTyX-Linux is what I will use in the end - I still have to see how it works out for my needs.

> About your fork, why not. For me you where too fast, I couln'd follow all your pull requests

Yes, this is what I meant that it might not be good to make big changes to a well tested systems without carefully checking each pull request. That's why it is probably better I test the new things in a separate fork.

Anyway, will still contribute to NuTyX-Linux :+1:  and thanks again for being so kind to answer my questions.
