### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by peter1000** [NuTyX/houaphan#9]
hi,

just tried to install **NuTyX** following the english version.

1. I followed the suggestion here: https://github.com/NuTyX/houaphan/blob/master/www/en/index.html#L56 pointing me to [generate-iso.html](http://www.nutyx.org/en/generate-iso.html).

*Observation:* somewere it would be good to mention that one has to enter the chroot to issue some of the commands in step `2. Generate the ISO`

e.g. `cards purge` will not work if one starts with an other distribution: e.g. Arch Linux.

Cheers
P

**Comment by tnut** [comment]
I agreed, it need to be clarify. (like on the french version)
